#!/usr/bin/env bash
# This script configures Nginx to have a custom 404 page

# Update package lists
apt-get update

# Install Nginx
apt-get -y install nginx

# Ensure Nginx is listening on port 80
sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;/' /etc/nginx/nginx.conf

# Create a default index.html file with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Create a custom 404 page with the specified content
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to use the custom 404 page
cat << EOF > /etc/nginx/sites-available/not_found_page_404
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Enable the site
ln -s /etc/nginx/sites-available/not_found_page_404 /etc/nginx/sites-enabled/

# Test Nginx configuration
nginx -t

# Restart Nginx to apply changes
systemctl restart nginx