#!/usr/bin/env bash
# This script configures HAProxy as a load balancer for two web servers

# Define the IP addresses of your web servers
WEB_SERVER_1=54.236.25.139
WEB_SERVER_2=100.26.175.211

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get -y install haproxy

# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # Default ciphers to use on SSL-enabled listening sockets.
    # For more information, see ciphers(1SSL). This list is from:
    #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
    ssl-default-bind-ciphers PROFILE=SYSTEM
    ssl-default-bind-options no-sslv3

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 525092-web-01 $WEB_SERVER_1:80 check
    server w $WEB_SERVER_2:80 check

listen stats
    bind :8080
    stats enable
    stats uri /stats
    stats refresh 10s
    stats auth admin:password
EOF

# Test HAProxy configuration for syntax errors
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the new configuration
sudo systemctl restart haproxy

echo "HAProxy configured as a load balancer for the two web servers."