#!/usr/bin/env bash
# Bash script that generates a MySQL dump
MYSQL_PASSWORD=$1
BACKUP_FILE="backup.sql"
DATE=$(date +%d-%m-%Y)
ARCHIVE_FILE="${DATE}.tar.gz"
mysqldump -u root -p"${MYSQL_PASSWORD}" --all-databases > "${BACKUP_FILE}"
tar -czvf "${ARCHIVE_FILE}" "${BACKUP_FILE}"
