#!/usr/bin/env bash
# Script to configure Nginx to listen on port 80 on all active IPv4 IPs
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/listen 80 default_server/\nlisten 80/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server/\nlisten \[::\]:80/' /etc/nginx/sites-available/default
sudo service nginx stop