#!/usr/bin/env bash
# Bash script to display specific information from /etc/passwd using while loop + IFS

# Open /etc/passwd for reading
while IFS=: read -r username _ uid gid gecos home shell; do
    # Extract additional information from gecos field
    IFS=',' read -r _ _ _ info _ <<< "$gecos"
    IFS=' ' read -r _ _ _ _ passcode _ <<< "$info"

    # Display user information in the expected format
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $gid's place is protected by the passcode $passcode, more info about the user here: $username"
done </etc/passwd