#!/usr/bin/env bash
# This script displays numbers from 1 to 20, and for the 4th, 9th, and 17th iterations,
# it displays a special message related to bad luck from different countries.

i=1
while [ $i -le 20 ]; do
    case $i in
        4)
            echo "$i"
            echo "bad luck from China"
            ;;
        9)
            echo "$i"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$i"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    
    ((i++))
done